version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: banking-db
    environment:
      POSTGRES_USER: banking-db
      POSTGRES_PASSWORD: banking
      POSTGRES_DB: banking
    ports:
        - "5432:5432"
